const Discord = require("discord.js");
const mars = new Discord.Client();
const mars2 = new Discord.Client();
const mars3 = new Discord.Client();
const mars4 = new Discord.Client();
const mars5 = new Discord.Client();
const mars6 = new Discord.Client();
const mars7 = new Discord.Client();
const mars8 = new Discord.Client();
const mars9 = new Discord.Client();
const mars10 = new Discord.Client();
const mars11 = new Discord.Client();
const mars12 = new Discord.Client();
const mars13 = new Discord.Client();
const mars14 = new Discord.Client();
const mars15 = new Discord.Client();
const mars16 = new Discord.Client();
const mars17 = new Discord.Client();
const mars18 = new Discord.Client();
const mars19 = new Discord.Client();
const mars20 = new Discord.Client();
const mars21 = new Discord.Client();
const mars22 = new Discord.Client();
const mars23 = new Discord.Client();
const mars24 = new Discord.Client();
const mars25 = new Discord.Client();
const mars26 = new Discord.Client();
const mars27 = new Discord.Client();
const mars28 = new Discord.Client();
const mars29 = new Discord.Client();
const mars30 = new Discord.Client();
const mars31 = new Discord.Client();
const mars32 = new Discord.Client();
const mars33 = new Discord.Client();
const mars34 = new Discord.Client();
const mars35 = new Discord.Client();
const mars36 = new Discord.Client();
const mars37 = new Discord.Client();
const mars38 = new Discord.Client();
const mars39 = new Discord.Client();
const mars40 = new Discord.Client();
const mars41 = new Discord.Client();
const mars42 = new Discord.Client();
const mars43 = new Discord.Client();
const mars44 = new Discord.Client();
const mars45 = new Discord.Client();
const mars46 = new Discord.Client();
const mars47 = new Discord.Client();
const mars48 = new Discord.Client();
const mars49 = new Discord.Client();
const mars50 = new Discord.Client();
const mars51 = new Discord.Client();
const mars52 = new Discord.Client();
const mars53 = new Discord.Client();
const mars54 = new Discord.Client();
const mars55 = new Discord.Client();
const mars56 = new Discord.Client();
const mars57 = new Discord.Client();
const mars58 = new Discord.Client();
const mars59 = new Discord.Client();
const mars60 = new Discord.Client();
const mars61 = new Discord.Client();
const mars62 = new Discord.Client();
const mars63 = new Discord.Client();
const mars64 = new Discord.Client();
const mars65 = new Discord.Client();
const mars66 = new Discord.Client();
const mars67 = new Discord.Client();
const mars68 = new Discord.Client();
const mars69 = new Discord.Client();
const mars70 = new Discord.Client();
const mars71 = new Discord.Client();
const mars72 = new Discord.Client();
const mars73 = new Discord.Client();
const mars74 = new Discord.Client();
const mars75 = new Discord.Client();
const mars76 = new Discord.Client();
const mars77 = new Discord.Client();
const mars78 = new Discord.Client();
const mars79 = new Discord.Client();
const mars80 = new Discord.Client();
const mars81 = new Discord.Client();
const mars82 = new Discord.Client();
const mars83 = new Discord.Client();
const mars84 = new Discord.Client();
const mars85 = new Discord.Client();
const mars86 = new Discord.Client();
const mars87 = new Discord.Client();
const mars88 = new Discord.Client();
const mars89 = new Discord.Client();
const mars90 = new Discord.Client();
const mars91 = new Discord.Client();
const mars92 = new Discord.Client();
const mars93 = new Discord.Client();
const mars94 = new Discord.Client();
const mars95 = new Discord.Client();
const mars96 = new Discord.Client();
const mars97 = new Discord.Client();
const mars98 = new Discord.Client();
const mars99 = new Discord.Client();
const mars100 = new Discord.Client();
const mars101 = new Discord.Client();
const mars102 = new Discord.Client();
const mars103 = new Discord.Client();
const mars104 = new Discord.Client();
const mars105 = new Discord.Client();
const mars106 = new Discord.Client();
const mars107 = new Discord.Client();
const mars108 = new Discord.Client();
const mars109 = new Discord.Client();
const mars110 = new Discord.Client();
const mars111 = new Discord.Client();
const mars112 = new Discord.Client();
const mars113 = new Discord.Client();
const mars114 = new Discord.Client();
const mars115 = new Discord.Client();
const mars116 = new Discord.Client();
const mars117 = new Discord.Client();
const mars118 = new Discord.Client();
const mars119 = new Discord.Client();
const mars120 = new Discord.Client();
const mars121 = new Discord.Client();
const mars122 = new Discord.Client();
const mars123 = new Discord.Client();
const mars124 = new Discord.Client();
const mars125 = new Discord.Client();
const mars126 = new Discord.Client();
const mars127 = new Discord.Client();
const mars128 = new Discord.Client();
const mars129 = new Discord.Client();
const mars130 = new Discord.Client();
const mars131 = new Discord.Client();
const mars132 = new Discord.Client();
const mars133 = new Discord.Client();
const mars134 = new Discord.Client();
const mars135 = new Discord.Client();
const mars136 = new Discord.Client();
const mars137 = new Discord.Client();
const mars138 = new Discord.Client();
const mars139 = new Discord.Client();
const mars140 = new Discord.Client();
const mars141 = new Discord.Client();
const mars142 = new Discord.Client();
const mars143 = new Discord.Client();
const mars144 = new Discord.Client();
const mars145 = new Discord.Client();
const mars146 = new Discord.Client();
const mars147 = new Discord.Client();
const mars148 = new Discord.Client();
const mars149 = new Discord.Client();
const mars150 = new Discord.Client();
const mars151 = new Discord.Client();
const mars152 = new Discord.Client();
const mars153 = new Discord.Client();
const mars154 = new Discord.Client();
const mars155 = new Discord.Client();
const mars156 = new Discord.Client();
const mars157 = new Discord.Client();
const mars158 = new Discord.Client();
const mars159 = new Discord.Client();
const mars160 = new Discord.Client();
const mars161 = new Discord.Client();
const mars162 = new Discord.Client();
const mars163 = new Discord.Client();
const mars164 = new Discord.Client();
const mars165 = new Discord.Client();
const mars166 = new Discord.Client();
const mars167 = new Discord.Client();
const mars168 = new Discord.Client();
const mars169 = new Discord.Client();
const mars170 = new Discord.Client();
const mars171 = new Discord.Client();
const mars172 = new Discord.Client();
const mars173 = new Discord.Client();
const mars174 = new Discord.Client();
const mars175 = new Discord.Client();
const mars176 = new Discord.Client();
const mars177 = new Discord.Client();
const mars178 = new Discord.Client();
const mars179 = new Discord.Client();
const mars180 = new Discord.Client();
const mars181 = new Discord.Client();
const mars182 = new Discord.Client();
const mars183 = new Discord.Client();
const mars184 = new Discord.Client();
const mars185 = new Discord.Client();
const mars186 = new Discord.Client();
const mars187 = new Discord.Client();
const mars188 = new Discord.Client();
const mars189 = new Discord.Client();
const mars190 = new Discord.Client();
const mars191 = new Discord.Client();
const mars192 = new Discord.Client();
const mars193 = new Discord.Client();
const mars194 = new Discord.Client();
const mars195 = new Discord.Client();
const mars196 = new Discord.Client();
const mars197 = new Discord.Client();
const mars198 = new Discord.Client();
const mars199 = new Discord.Client();
const mars200 = new Discord.Client();
const mars201 = new Discord.Client();
const mars202 = new Discord.Client();
const mars203 = new Discord.Client();
const mars204 = new Discord.Client();
const mars205 = new Discord.Client();
const mars206 = new Discord.Client();
const mars207 = new Discord.Client();
const mars208 = new Discord.Client();
const mars209 = new Discord.Client();
const mars210 = new Discord.Client();
const mars211 = new Discord.Client();
const mars212 = new Discord.Client();
const mars213 = new Discord.Client();
const mars214 = new Discord.Client();
const mars215 = new Discord.Client();
const mars216 = new Discord.Client();
const mars217 = new Discord.Client();
const mars218 = new Discord.Client();
const mars219 = new Discord.Client();
const mars220 = new Discord.Client();
const mars221 = new Discord.Client();
const mars222 = new Discord.Client();
const mars223 = new Discord.Client();
const mars224 = new Discord.Client();
const mars225 = new Discord.Client();
const mars226 = new Discord.Client();
const mars227 = new Discord.Client();
const mars228 = new Discord.Client();
const mars229 = new Discord.Client();
const mars230 = new Discord.Client();
const mars231 = new Discord.Client();
const mars232 = new Discord.Client();
const mars233 = new Discord.Client();
const mars234 = new Discord.Client();
const mars235 = new Discord.Client();
const mars236 = new Discord.Client();
const mars237 = new Discord.Client();
const mars238 = new Discord.Client();
const mars239 = new Discord.Client();
const mars240 = new Discord.Client();
const mars241 = new Discord.Client();
const mars242 = new Discord.Client();
const mars243 = new Discord.Client();
const mars244 = new Discord.Client();
const mars245 = new Discord.Client();
const mars246 = new Discord.Client();
const mars247 = new Discord.Client();
const mars248 = new Discord.Client();
const mars249 = new Discord.Client();
const mars250 = new Discord.Client();


rs.login("");
mars2.login(""ODIxMTIzNDA0NDc1OTI0NTEy.YE_I5Q.QzH6g1QnHSz4uCqfh15s52zinSA"");
mars3.login("");
mars4.login("");
mars5.login("");
mars6.login("");
mars7.login("");
mars8.login("");
mars9.login("");
mars10.login("");
mars11.login("");
mars12.login("");
mars13.login("");
mars14.login("");
mars15.login("");
mars16.login("");
mars17.login("");
mars18.login("");
mars19.login("");
mars20.login("");
mars21.login("");
mars22.login("");
mars23.login("");
mars24.login("");
mars25.login("");
mars26.login("");
mars27.login("");
mars28.login("");
mars29.login("");
mars30.login("");
mars31.login("");
mars32.login("");
mars33.login("");
mars34.login("");
mars35.login("");
mars36.login("");
mars37.login("");
mars38.login("");
mars39.login("");
mars40.login("");
mars41.login("");
mars42.login("");
mars43.login("");
mars44.login("");
mars45.login("");
mars46.login("");
mars47.login("");
mars48.login("");
mars49.login("");
mars50.login("");
mars51.login("");
mars52.login("");
mars53.login("");
mars54.login("");
mars55.login("");
mars56.login("");
mars57.login("");
mars58.login("");
mars59.login("");
mars60.login("");
mars61.login("");
mars62.login("");
mars63.login("");
mars64.login("");
mars65.login("");
mars66.login("");
mars67.login("");
mars68.login("");
mars69.login("");
mars70.login("");
mars71.login("");
mars72.login("");
mars73.login("");
mars74.login("");
mars75.login("");
mars76.login("");
mars77.login("");
mars78.login("");
mars79.login("");
mars80.login("");
mars81.login("");
mars82.login("");
mars83.login("");
mars84.login("");
mars85.login("");
mars86.login("");
mars87.login("");
mars88.login("");
mars89.login("");
mars90.login("");
mars91.login("");
mars92.login("");
mars93.login("");
mars94.login("");
mars95.login("");
mars96.login("");
mars97.login("");
mars98.login("");
mars99.login("");
mars100.login("");
mars101.login("");
mars102.login("");
mars103.login("");
mars104.login("");
mars105.login("");
mars106.login("");
mars107.login("");
mars108.login("");
mars109.login("");
mars110.login("");
mars111.login("");
mars112.login("");
mars113.login("");
mars114.login("");
mars115.login("");
mars116.login("");
mars117.login("");
mars118.login("");
mars119.login("");
mars120.login("");
mars121.login("");
mars122.login("");
mars123.login("");
mars124.login("");
mars125.login("");
mars126.login("");
mars127.login("");
mars128.login("");
mars129.login("");
mars130.login("");
mars131.login("");
mars132.login("");
mars133.login("");
mars134.login("");
mars135.login("");
mars136.login("");
mars137.login("");
mars138.login("");
mars139.login("");
mars140.login("");
mars141.login("");
mars142.login("");
mars143.login("");
mars144.login("");
mars145.login("");
mars146.login("");
mars147.login("");
mars148.login("");
mars149.login("");
mars150.login("");
mars151.login("");
mars152.login("");
mars153.login("");
mars154.login("");
mars155.login("");
mars156.login("");
mars157.login("");
mars158.login("");
mars159.login("");
mars160.login("");
mars161.login("");
mars162.login("");
mars163.login("");
mars164.login("");
mars165.login("");
mars166.login("");
mars167.login("");
mars168.login("");
mars169.login("");
mars170.login("");
mars171.login("");
mars172.login("");
mars173.login("");
mars174.login("");
mars175.login("");
mars176.login("");
mars177.login("");
mars178.login("");
mars179.login("");
mars180.login("");
mars181.login("");
mars182.login("");
mars183.login("");
mars184.login("");
mars185.login("");
mars186.login("");
mars187.login("");
mars188.login("");
mars189.login("");
mars190.login("");
mars191.login("");
mars192.login("");
mars193.login("");
mars194.login("");
mars195.login("");
mars196.login("");
mars197.login("");
mars198.login("");
mars199.login("");
mars200.login("");
mars201.login("");
mars202.login("");
mars203.login("");
mars204.login("");
mars205.login("");
mars206.login("");
mars207.login("");
mars208.login("");
mars209.login("");
mars210.login("");
mars211.login("");
mars212.login("");
mars213.login("");
mars214.login("");
mars215.login("");
mars216.login("");
mars217.login("");
mars218.login("");
mars219.login("");
mars220.login("");
mars221.login("");
mars222.login("");
mars223.login("");
mars224.login("");
mars225.login("");
mars226.login("");
mars227.login("");
mars228.login("");
mars229.login("");
mars230.login("");
mars231.login("");
mars232.login("");
mars233.login("");
mars234.login("");
mars235.login("");
mars236.login("");
mars237.login("");
mars238.login("");
mars239.login("");
mars240.login("");
mars241.login("");
mars242.login("");
mars243.login("");
mars244.login("");
mars245.login("");
mars246.login("");
mars247.login("");
mars248.login("");
mars249.login("");
mars250.login("");
